# Generated by Django 2.2.5 on 2019-10-31 02:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['card_type', 'card_number']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['category']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.AddField(
            model_name='transaction',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('account', 'Account'), ('credit', 'Credit Card'), ('debit', 'Debit Card'), ('bank', 'Bank')], default='Account', max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MaxLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('credit', 'Credit Card'), ('debit', 'Debit Card')], max_length=45),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('bank', 'Bank Transactions'), ('utilities', 'Bills & Utilities'), ('transportation', 'Auto & Transport'), ('groceries', 'Groceries'), ('shopping', 'Shopping'), ('health', 'Healthcare'), ('education', 'Education'), ('travel', 'Travel'), ('housing', 'Housing'), ('entertainment', 'Entertainment'), ('others', 'Others')], max_length=45),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('pay', 'Pay'), ('request', 'Request'), ('transfer', 'Transfer')], default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='bank',
            unique_together={('routing_number', 'account_number')},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('first_name', 'last_name', 'email')},
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_owner', to='app.User'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='app.Account'),
        ),
    ]
