# Generated by Django 2.2.5 on 2019-12-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191208_0833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
